# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://parevalo.github.io/
baseurl: /parevalo.github.io/
title: Paulo Arévalo
author: Paulo Arévalo
description: Personal info and resume
avatar: profile.jpg
email: parevalo@bu.edu
github: parevalo
linkedin: arevalopaulo
google_analytics: UA-115076349-1


# needed for travis-ci build
exclude: [vendor]
